version: "3.8"

services:
  db:
    image: postgres:14.2-alpine
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: springbootdb
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - /tmp

volumes:
  localstack-vol:
