version: "3.8"
services:
  db:
    image: postgres:14.2-alpine
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: springbootdb
      POSTGRES_USER: luis
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - "./localenv/db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql"

volumes:
  localstack-vol:
