spring:
  application:
    name: payment-ms
#    jpa:
#      properties:
#        hibernate:
#          default_schema: payment
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springbootdb?currentSchema=payment
    username: luis
    password: 12345
    # JPA properties
    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false
      generate-ddl: true
  flyway:
    defaultSchema: payment

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
  instance:
    instance-id: ${spring.application.name}:${random.int}

resilience4j:
  circuitbreaker:
    instances:
      updateOrder:
        slidingWindowSize: 3
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 50s